<?php 
// echo '<pre> $_GET: ';
// 	print_r($_GET);
// echo '</pre>';
// echo '<pre> $usuario: ';
// // print_r ($usuario);
// // echo '</pre>';
// echo '<pre> $filas: ';
// print_r ($filas);
// echo '</pre>';


?>
<h2 class="sub-header">/application/views/users/select_duty.phtml</h2>
<a href="?action=insert_duty">nueva tarea</a>
<br/>
<table class="table table-striped">
<?php

foreach($filas as $key => $fila):?>
	<tr>
		<?php 
		foreach ($fila as $columna):?>
			<td><?=$columna;?></td>
		<?php endforeach; ?>

		<td>
			<a href="?action=update_duty&id=<?=$fila['iduser'];?>">Update</a>
				&nbsp;
			<a href="?action=delete_duty&id=<?=$fila['iduser'];?>">Delete</a>
				&nbsp;
		</td>
	</tr>
<?php endforeach ?>
</table>