


<h2 class="sub-header">Usuarios</h2>
<a href="?action=insert">Insertar Usuario</a>
<br/>
<table class="table table-striped">
<?php

foreach($filas as $key => $fila):?>
	<tr>
		<?php 
		$image = $fila['photo'];
		unset($fila['photo']);
		foreach ($fila as $columna):?>
			<td><?=$columna;?></td>
		<?php endforeach; ?>
		<td>
			<img width="75px" src="<?='/uploads/'.$image;?>"/>
		</td>	
		<td>
			<a href="?action=update&id=<?=$fila['iduser'];?>">Update</a>
				&nbsp;
			<a href="?action=delete&id=<?=$fila['iduser'];?>">Delete</a>
				&nbsp;
			<a href="?action=insert_duty&id=<?=$fila['iduser'];?>">New duty</a>
		</td>
	</tr>
<?php endforeach ?>
</table>