


<h2 class="sub-header">Projectos</h2>
<a href="?action=insert">Insertar Proyecto</a>
<br/>
<table class="table table-striped">
<?php
// 	echo '<pre>: $_GET:';
// 		print_r($_GET);
// 	echo '</pre>'.'</br>';

// 	echo '<pre>: $_POST:';
// 	print_r($_POST);
// 	echo '</pre>'.'</br>';

// 	echo '<pre>: $_FILES:';
// 	print_r($_FILES);
// 	echo '</pre>'.'</br>';
//  	die;

foreach($filas as $key => $fila):?>
	<tr>
		<?php 
		foreach ($fila as $columna):?>
			<td><?=$columna;?></td>
		<?php endforeach; ?>

		<td>
			<a href="?action=update&id=<?=$fila['iduser'];?>">Update</a>
				&nbsp;
			<a href="?action=delete&id=<?=$fila['iduser'];?>">Delete</a>
				&nbsp;
		</td>
	</tr>
<?php endforeach ?>
</table>