<h2 class="sub-header">Usuarios</h2>
<a href="users.php?action=insert">Insertar Usuario</a>
<br/>
<table class="table table-striped">
<?php foreach($filas as $key => $fila):?>
	<tr>
		<?php 
		$image = $fila['photo'];
		unset($fila['photo']);
		foreach ($fila as $columna):?>
			<td><?=$columna;?></td>
		<?php endforeach; ?>
		<td>
			<img width="100px" src="<?='/uploads/'.$image;?>"/>
		</td>	
		<td>
			<a href="users.php?action=update&id=<?=$key;?>">Update</a>
				&nbsp;
			<a href="users.php?action=delete&id=<?=$key;?>">Delete</a>
		</td>
	</tr>
<?php endforeach ?>
</table>