
          <ul class="nav nav-sidebar">
          <!-- manage_duties is on 'public' temporary until I figure out
          					how to write the correct call from here -->
          	<li class="active"><a href="users.php">usuarios</a></li>
          	<li><a href="?action=select_project">projectos</a></li>
          	<li><a href="?action=select_duty">tareas</a></li>
                   
          </ul>
          
          
     