
<h2 class="sub-header">select_project.phtml</h2>
<a href="?action=insert">Insertar Proyecto</a>
<br/>
<table class="table table-striped">
<?php

foreach($filas as $key => $fila):?>
	<tr>
		<?php 
		foreach ($fila as $columna):?>
			<td><?=$columna;?></td>
		<?php endforeach; ?>

		<td>
			<a href="?action=update&id=<?=$fila['iduser'];?>">Update</a>
				&nbsp;
			<a href="?action=delete&id=<?=$fila['iduser'];?>">Delete</a>
				&nbsp;
		</td>
	</tr>
<?php endforeach ?>
</table>